
//客户信息列表

const customerList = [
  { customerGuid: 'customer_111',
    tenantGuid: '111',
    customerName: '海格物流',
    customerShortName: '海格',
    customerEnglishName: 'logistics_hercules',
    contactHeaderInformation: '111',
    customerTelephone: '111',
    customerFax: '111',
    customerAddress: '111',
    creditCode: '111',
    customerCountry: '111',
    customerProvince: '111',
    customerCity: '111',
    customerDistrict: '111',
    customerStreet: '111',
    customerLongitude: 111,
    customerLatitude: 111,
    cooperationStatus: 1,
    isContract: 0,
    isNeedDebitNote: 0,
    salesPersonGuid: '111',
    isOrderingCustomer: 1,
    salesPersonName: '小李子'
  },
  { customerGuid: 'customer_222',
    tenantGuid: '111',
    customerName: '顺风快递',
    customerShortName: '顺风',
    customerEnglishName: 'shunfeng',
    contactHeaderInformation: '222',
    customerTelephone: '222',
    customerFax: '222',
    customerAddress: '222',
    creditCode: '222',
    customerCountry: '222',
    customerProvince: '222',
    customerCity: '222',
    customerDistrict: '222',
    customerStreet: '222',
    customerLongitude: 222,
    customerLatitude: 222,
    customerDescribe: '222',
    cooperationStatus: 1,
    isContract: 222,
    contractStartDate: [Object],
    contractEndDate: [Object],
    balanceMode: 222,
    currency: '222',
    creditDay: '222',
    creditLimit: 222,
    advanceLimit: 222,
    lastCheckAccountDate: '222222',
    paymentDate: '222',
    invoiceDescribe: '222',
    isNeedDebitNote: 222,
    salesPersonGuid: '111',
    supplyGuid: '222',
    isAgent: 222,
    isInternal: 222,
    relationCustomerCode: '222222222',
    isOrderingCustomer: 1,
    salesPersonName: '小李子'
  }
];

export default customerList;
